use anyhow::anyhow;
use axum::{
    extract::{Path, State},
    http::StatusCode,
    routing::{get, post},
    Json, Router,
};
use candid::{CandidType, Decode, Encode};
use gloo_timers::future::TimeoutFuture;
use ic_agent::{
    agent::{CallResponse, RejectResponse, ReplyResponse, RequestStatusResponse},
    export::Principal,
    Agent, Certificate,
};
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeMap,
    result::Result,
    sync::{Arc, LazyLock},
    time::Duration,
};
use tower_http::cors::{Any, CorsLayer};
use tower_service::Service;
use worker::*;

static SCROLLS_BITCOIN: LazyLock<Principal> = LazyLock::new(|| {
    let canister_ids_json = include_str!("../../../canister_ids.json");
    let canister_ids: serde_json::Value = serde_json::from_str(canister_ids_json).unwrap();
    let canister_id = canister_ids["scrolls_bitcoin"]["ic"].as_str().unwrap();
    Principal::from_text(canister_id).unwrap()
});

/// Creates a permissive CORS configuration layer for the API server.
///
/// This configuration:
/// - Allows requests from any origin
/// - Allows all HTTP methods
/// - Allows all headers to be sent
/// - Exposes all headers to the client
/// - Sets a max age of 1 hour (3600 seconds) for preflight requests
fn cors_layer() -> CorsLayer {
    CorsLayer::new()
        .allow_origin(Any)
        .allow_methods(Any)
        .allow_headers(Any)
        .expose_headers(Any)
        .max_age(Duration::from_secs(3600))
}

#[derive(Clone)]
pub struct AppState {
    pub agent: Arc<Agent>,
}

fn create_agent() -> anyhow::Result<Agent> {
    let agent = Agent::builder().with_url("https://ic0.app").build()?;
    Ok(agent)
}

fn router(state: AppState) -> Router {
    Router::new()
        .route("/", get(root))
        .route("/config", get(config))
        .route("/{network}/address/{nonce}", get(address))
        .route("/{network}/sign", post(sign))
        .with_state(state)
        .layer(cors_layer())
}

#[event(fetch)]
async fn fetch(
    req: HttpRequest,
    _env: Env,
    _ctx: Context,
) -> worker::Result<axum::http::Response<axum::body::Body>> {
    let agent = create_agent().map_err(|e| format!("System error: {}", e.to_string()))?;
    let state = AppState {
        agent: Arc::new(agent),
    };
    Ok(router(state).call(req).await?)
}

const SCROLLS_BITCOIN_GREETING: &'static str = r#"# Scrolls Bitcoin API is here!


Scrolls will sign transactions spending from addresses generated by this API. The flow is as follows:

1. Generate a Scrolls address (or a few).
2. Send BTC and/or Charms to the address(es). They are now locked.
3. To unlock, sign the spending transaction with Scrolls. Only transactions carrying correct spells will be signed.


## `GET /config`

Returns the current configuration of the Scrolls Bitcoin API as JSON.
'''json
{
  "fee_address": {
    "main": "bc1qxxxjm06n50uugxewxe5r5w5tskqwq4gkwrm0al",
    "testnet4": "tb1qrk6da5g0592sx6lmgpchaf5qy2lgn8am7cuf3a"
  },
  "fee_per_input": 64,
  "fee_basis_points": 10,
  "fixed_cost": 895
}
'''

Scrolls will only sign transactions if they have a fee output paid to `fee_address`. The fee is calculated as follows:
`fee = fixed_cost + fee_per_input * number_of_inputs + fee_basis_points / 10000 * total_input_sats`


## `GET /{network}/address/{nonce}`

Returns the address derived for `nonce` (64-bit unsigned integer) on `network` ("main" or "testnet4").
The nonce is used to derive the address deterministically: the same nonce always results in the same address
on the same network.

The returned address is a JSON string value (in double quotes).


## `POST /{network}/sign`

```json
{
  "sign_inputs": [
    {
      "index": 0,
      "nonce": 1234567890
    },
    {
      "index": 1,
      "nonce": 1234567890"
    }
  ],
  "prev_txs": ["020000000001025a...529219c900000000", "0200000001b1d12d...b0645dc000000000"],
  "tx_to_sign": "0200000001b1d12d...b0645dc000000000"
}
```

Signs `tx_to_sign` and returns the signed transaction as a hex-encoded string for `network` ("main" or "testnet4").
The `sign_inputs` array contains the indices of the inputs to sign. The `prev_txs` array contains hex encoded
transactions creating the outputs that `tx_to_sign` spends.

The returned signed transaction is a JSON string value (in double quotes).

"#;

pub async fn root() -> &'static str {
    SCROLLS_BITCOIN_GREETING
}

pub type BitcoinAddresses = BTreeMap<String, String>;

#[derive(CandidType, Clone, Debug, Deserialize, Serialize)]
pub struct Config {
    pub fee_address: BitcoinAddresses,

    pub fee_per_input: u64,
    pub fee_basis_points: u64,
    pub fixed_cost: u64,
}

#[worker::send]
pub async fn config(
    State(app_state): State<AppState>,
) -> Result<Json<Config>, (StatusCode, String)> {
    let agent = app_state.agent.clone();
    let response = agent
        .query(&SCROLLS_BITCOIN, "config")
        .call()
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("System error: querying config: {}", e),
            )
        })?;
    let config = Decode!(&response, Config).map_err(|e| {
        (
            StatusCode::BAD_GATEWAY,
            format!("System error: decoding config: {}", e),
        )
    })?;

    Ok(Json(config))
}

#[worker::send]
pub async fn address(
    State(app_state): State<AppState>,
    Path((network, nonce)): Path<(String, u64)>,
) -> Result<Json<String>, (StatusCode, String)> {
    let agent = app_state.agent.clone();
    let update_response = agent
        .update(&SCROLLS_BITCOIN, "address")
        .with_arg(Encode!(&network, &nonce).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("System error: encoding address request: {}", e),
            )
        })?)
        .call()
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("System error: calling address method: {}", e),
            )
        })?;
    let response = wait_for_response(agent, update_response)
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("System error: waiting for response: {}", e),
            )
        })?;
    let result = Decode!(&response, Result<String, String>)
        .map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("System error: decoding address response: {}", e),
            )
        })?
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("Upstream error: {}", e)))?;
    Ok(Json(result))
}

async fn wait_for_response(
    agent: Arc<Agent>,
    update_response: CallResponse<(Vec<u8>, Certificate)>,
) -> anyhow::Result<Vec<u8>> {
    match update_response {
        CallResponse::Response((response, ..)) => Ok(response),
        CallResponse::Poll(request_id) => loop {
            let (request_status, _) = agent
                .request_status_raw(&request_id, *SCROLLS_BITCOIN)
                .await?;
            match request_status {
                RequestStatusResponse::Unknown => {}
                RequestStatusResponse::Received => {}
                RequestStatusResponse::Processing => {}
                RequestStatusResponse::Replied(ReplyResponse { arg }) => {
                    break Ok(arg);
                }
                RequestStatusResponse::Rejected(RejectResponse {
                    reject_code,
                    reject_message,
                    ..
                }) => {
                    break Err(anyhow!(
                        "Request rejected: code {reject_code:?}: {reject_message}"
                    ))
                }
                RequestStatusResponse::Done => {
                    break Err(anyhow!("Request is done but no reply received"))
                }
            };
            TimeoutFuture::new(1000).await;
        },
    }
}

#[derive(CandidType, Clone, Debug, Deserialize, Serialize)]
pub struct SignInput {
    pub index: usize,
    pub nonce: u64,
}

#[derive(CandidType, Clone, Debug, Deserialize, Serialize)]
pub struct SignRequest {
    pub sign_inputs: Vec<SignInput>,
    pub prev_txs: Vec<String>,
    pub tx_to_sign: String,
}

#[worker::send]
pub async fn sign(
    State(app_state): State<AppState>,
    Path(network): Path<String>,
    Json(sign_request): Json<SignRequest>,
) -> Result<Json<String>, (StatusCode, String)> {
    let agent = app_state.agent.clone();
    let update_response = agent
        .update(&SCROLLS_BITCOIN, "sign")
        .with_arg(Encode!(&network, &sign_request).map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("System error: encoding sign request: {}", e),
            )
        })?)
        .call()
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("System error: calling sign method: {}", e),
            )
        })?;
    let response = wait_for_response(agent, update_response)
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("System error: waiting for response: {}", e),
            )
        })?;
    let result = Decode!(&response, Result<String, String>)
        .map_err(|e| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("System error: decoding sign response: {}", e),
            )
        })?
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("Upstream error: {}", e)))?;
    Ok(Json(result))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_canister_id() {
        let canister_id = SCROLLS_BITCOIN.to_string();
        assert_eq!(canister_id, "lmbwh-3qaaa-aaaak-qunha-cai");
    }
}
