use proc_macro::TokenStream;

/// No-op stub for `wasm_bindgen` attribute macro.
///
/// Strips extern blocks (JS FFI declarations that don't exist on ICP). For
/// structs/enums, prepends `#[derive(BindgenedStruct)]` so that field-level
/// `#[wasm_bindgen(skip)]` / `#[wasm_bindgen(getter_with_clone)]` etc. are
/// recognised as helper attributes — without this, rustc rejects them as
/// proc-macro attribute calls in field position. Mirrors how the real
/// `wasm-bindgen-macro` declares `BindgenedStruct` with
/// `attributes(wasm_bindgen)`.
#[proc_macro_attribute]
pub fn wasm_bindgen(_attr: TokenStream, input: TokenStream) -> TokenStream {
    let input_str = input.to_string();
    let trimmed = input_str.trim_start();
    if trimmed.starts_with("extern") || trimmed.starts_with("pub extern") {
        return TokenStream::new();
    }
    if is_struct_or_enum(&input_str) {
        let mut out: TokenStream = "#[derive(::wasm_bindgen::__rt::BindgenedStruct)]"
            .parse()
            .unwrap();
        out.extend(input);
        return out;
    }
    input
}

/// True if the top-level item is a struct/enum/union (after skipping any
/// leading outer attributes like `#[derive(...)]` and doc comments).
fn is_struct_or_enum(src: &str) -> bool {
    let mut tokens = src.split_whitespace();
    while let Some(tok) = tokens.next() {
        match tok {
            "struct" | "enum" | "union" => return true,
            "impl" | "fn" | "const" | "static" | "trait" | "type" | "mod" | "use" | "extern" => {
                return false;
            }
            _ => continue,
        }
    }
    false
}

/// No-op stub for `__wasm_bindgen_class_marker` attribute macro.
#[proc_macro_attribute]
pub fn __wasm_bindgen_class_marker(_attr: TokenStream, input: TokenStream) -> TokenStream {
    input
}

/// No-op stub for `link_to` attribute macro.
#[proc_macro_attribute]
pub fn link_to(_attr: TokenStream, input: TokenStream) -> TokenStream {
    input
}

/// No-op derive that declares `wasm_bindgen` as a helper attribute so
/// `#[wasm_bindgen(skip)]` on struct fields type-checks. Generated by the
/// `wasm_bindgen` attribute macro above.
#[proc_macro_derive(BindgenedStruct, attributes(wasm_bindgen))]
pub fn bindgened_struct(_input: TokenStream) -> TokenStream {
    TokenStream::new()
}
