[package]
name = "toad-token"
version = "0.1.0"
edition = "2021"

[dependencies]
charms-data = { path = "../../charms-data" }
sp1-zkvm = { version = "3.0.0" }

[profile.release]
lto = "fat"
opt-level = "s"
strip = "symbols"
