[package]
name = "toad-token"
description = "A simple token Charms app"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
charms-sdk = { path = "../../charms-sdk", version = "0.2.0-dev" }

[profile.release]
lto = "fat"
opt-level = "s"
strip = "symbols"

[workspace]
