[package]
name = "toad-token-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toad-token-guest"
path = "src/lib.rs"

[features]
default = ["guest"]
guest = []

[dependencies]
charms-data = { path = "../../charms-data" }
jolt = { package = "jolt-sdk", git = "https://github.com/sigma0-dev/jolt", branch = "private-attribute" }

[profile.release]
codegen-units = 1
debug = 0
lto = "fat"
opt-level = "z"
panic = "abort"

[profile.test]
opt-level = 3
lto = "off"
