// SPDX-License-Identifier: MIT
pragma solidity 0.8.37;

import {Test} from "forge-std/Test.sol";

import {ICharmsTypes} from "../src/interfaces/ICharms.sol";
import {CborWellFormed} from "../src/libraries/CborWellFormed.sol";
import {CharmTokenClone, appKey} from "../src/libraries/CharmTokenClone.sol";
import {CharmsIds} from "../src/libraries/CharmsIds.sol";
import {SpellCodec} from "../src/libraries/SpellCodec.sol";

/// @notice Golden vectors from `charms_data::util::write` and `charms_client::tx::to_serialized_pv`,
/// generated by `cargo run --manifest-path ethereum/vectors/Cargo.toml`.
contract VectorsTest is Test {
    struct SpellVector {
        bytes32 anchor;
        uint256 chainId;
        address charms;
        bytes32 ethTxId;
        string name;
        bytes32 programVKey;
        bytes publicValues;
        ICharmsTypes.Spell spell;
        bytes spellCbor;
    }

    struct VaultVector {
        bytes32 appKey;
        uint256 chainId;
        address charms;
        bytes32 identity;
        address token;
    }

    struct TokenVector {
        ICharmsTypes.App app;
        bytes32 appKey;
        address charms;
        address implementation;
        address tokenAddress;
    }

    string internal constant SPELL_TYPES = "App(uint32 tag,bytes32 identity,bytes32 vk)"
        "BeamedOut(uint32 index,bytes32 destHash)Charm(uint32 app,uint64 amount,bytes data)"
        "Input(UtxoRef utxo,Charm[] charms,Pin[] pins)Output(address owner,Charm[] charms)"
        "Pin(bytes32 vk,uint32 version,bytes32 wasmHash)Spell(uint32 version,App[] apps,"
        "bytes[] publicInputs,Pin[] versionedApps,Input[] ins,UtxoRef[] refs,Output[] outs,"
        "BeamedOut[] beamedOuts,uint32[] scrolls)UtxoRef(bytes32 txId,uint32 index)";

    string internal json;

    function setUp() public {
        json = vm.readFile("test/vectors/spells.json");
    }

    function test_spellCborPublicValuesAndIdMatchRust() public view {
        SpellVector[] memory vectors = _spells();
        assertEq(vectors.length, 46);
        for (uint256 i; i < vectors.length; ++i) {
            SpellVector memory v = vectors[i];
            bytes memory cbor = SpellCodec.encode(v.spell);
            assertEq(cbor, v.spellCbor, v.name);
            assertEq(SpellCodec.publicValues(v.programVKey, cbor), v.publicValues, v.name);
            assertEq(
                SpellCodec.publicValuesLength(v.programVKey, cbor.length),
                v.publicValues.length,
                v.name
            );
            assertEq(CharmsIds.ethTxId(v.chainId, v.charms, v.anchor, cbor), v.ethTxId, v.name);
        }
    }

    function test_everyRustBlobIsOneWellFormedItem() public view {
        SpellVector[] memory vectors = _spells();
        uint256 blobs;
        for (uint256 i; i < vectors.length; ++i) {
            ICharmsTypes.Spell memory s = vectors[i].spell;
            for (uint256 a; a < s.publicInputs.length; ++a) {
                assertTrue(CborWellFormed.isSingleItem(s.publicInputs[a]), vectors[i].name);
                ++blobs;
            }
            for (uint256 o; o < s.outs.length; ++o) {
                for (uint256 c; c < s.outs[o].charms.length; ++c) {
                    bytes memory data = s.outs[o].charms[c].data;
                    if (data.length == 0) continue;
                    assertTrue(CborWellFormed.isSingleItem(data), vectors[i].name);
                    ++blobs;
                }
            }
        }
        assertGt(blobs, 100);
    }

    function test_vaultIdentityHasNoScaleByte() public view {
        bytes32 vaultVk = vm.parseJsonBytes32(json, "$.vaultVk");
        assertEq(vaultVk, sha256("charms/ethereum/vault/v1"));
        VaultVector[] memory vectors = abi.decode(
            vm.parseJsonTypeArray(
                json,
                "$.vaults",
                "VaultVector(bytes32 appKey,uint256 chainId,address charms,bytes32 identity,"
                "address token)"
            ),
            (VaultVector[])
        );
        assertEq(vectors.length, 4);
        for (uint256 i; i < vectors.length; ++i) {
            VaultVector memory v = vectors[i];
            bytes32 identity = CharmsIds.vaultIdentity(v.chainId, v.charms, v.token);
            assertEq(identity, v.identity);
            assertEq(appKey(ICharmsTypes.App(0x74, identity, vaultVk)), v.appKey);
        }
    }

    function test_tokenAddressIsCreate2OfTheCloneInitCode() public view {
        TokenVector[] memory vectors = abi.decode(
            vm.parseJsonTypeArray(
                json,
                "$.tokens",
                "TokenVector(App app,bytes32 appKey,address charms,address implementation,"
                "address tokenAddress)App(uint32 tag,bytes32 identity,bytes32 vk)"
            ),
            (TokenVector[])
        );
        assertEq(vectors.length, 4);
        for (uint256 i; i < vectors.length; ++i) {
            TokenVector memory v = vectors[i];
            assertEq(appKey(v.app), v.appKey);
            assertEq(CharmTokenClone.predict(v.charms, v.implementation, v.app), v.tokenAddress);
        }
    }

    function _spells() internal view returns (SpellVector[] memory) {
        return abi.decode(
            vm.parseJsonTypeArray(
                json,
                "$.spells",
                string.concat(
                    "SpellVector(bytes32 anchor,uint256 chainId,address charms,bytes32 ethTxId,"
                    "string name,bytes32 programVKey,bytes publicValues,Spell spell,"
                    "bytes spellCbor)",
                    SPELL_TYPES
                )
            ),
            (SpellVector[])
        );
    }
}
